### ISSUE TITLE
How to delete a single highlight?

### ISSUE THREAD

**Issue by 404pnf** [neisbut/textAnnotator#1]
I see a function, that's remove every highlight element.

``` js

/**
 * Removes annotation from element
 * @export
 */
tvs.ElementAnnoationInfo.prototype.remove = function() {
    goog.array.forEach(this.annotationElements, goog.dom.removeNode);
    delete this.annotetedElement[this.elPropName];
    this.annotetedElement = null;
};

```

Can I remove a single one by select / hover over an highlighted element and click on a "delete" tooltip?

Thank you!

**Comment by neisbut** [comment]
Hi! Thanks for your interest! I've exposed an unannotateElement function of Annotator.

```
$(document).on('click touch', '.tvs-annotated-text, .tvs-annotate-element', function(el) {
    u.unannotateElement(this);
});
```

You can see how it work on the gh-pages demo. Please check if it is what you need.

**Comment by 404pnf** [comment]
Wow, wow, wow!  It works and  it is very intuitive.  Thank you!

I am still wrapping my head on how you implement the whole thing.  It's amazing.

I am trying to mimic what kindle reader does: 1. select a range of text 2. tooltip pops up 3. click "Mark" or "Unmark".  I assumed there would be many js plugin to do this.  How wrong was I! 

Yours is the only one I found.

Thank you again!

**Comment by neisbut** [comment]
This is exactly what happened to me :) I also needed such thing and there were nothing available so I decided to do it by myself.
