### ISSUE TITLE
Why do the position:absolute divs exist?

### ISSUE THREAD

**Issue by x1024** [neisbut/textAnnotator#3]
I found this library after reading this article:
http://www.toptal.com/javascript/annotating-texts-on-the-web-using-svg

It seems that the text annotations are implemented via divs with position: absolute that are appended to the body. Those divs have a repeating SVG for a background image.
I tried it, and it was possible to simply set the background-image property of the <span class="highlighted">

The only downside I see is that using this it's only possible to have a single effect on a piece of text. However, this trivially fixes any resizing and text-movement issues.  

What is the rationale behind having position:absolute overlays versus simply setting the background of the <span>s?

**Comment by neisbut** [comment]
Hi, the shortest answer is: it uses not only repeating SVG, but stretching and combination as well, so background properties don't fit there.

**Comment by x1024** [comment]
One would think that "stretch" can be achieved with setting the correct background-size and/or percentage units in the SVG: http://codepen.io/Pavhan/pen/fnKHh
The same for repeating.
Combinations can be achieved by creating a more complex SVG(e.g. to combine one type of line and another, just place two <line>s in an SVG) and setting it as a background image.
